export const searchActionTypes = {
  GET_LOGS: 'GET_LOGS',
  LOADING: 'LOGS_LOADING',
  SET_AUTOREFRESH: 'SET_AUTOREFRESH',
  SET_LOGS: 'SET_LOGS',
  SET_QUERY: 'SET_QUERY',
  SET_SEARCH_PERIOD: 'SET_SEARCH_PERIOD',
  SET_CURRENT_APP_NAME: 'SET_CURRENT_APP_NAME'
};