export const accountActionTypes = {
  CLEAR_DATA: 'CLEAR_DATA',
  LOAD_PROFILE: 'LOAD_PROFILE',
  PROFILE_LOADED: 'PROFILE_LOADED',
  SET_AUTH_TYPE: 'SET_AUTH_TYPE',
  AUTHENTICATION_CHANGED: 'AUTHENTICATION_CHANGED'
};