export const aadAccountActionTypes = {
  AAD_AUTHENTICATED: 'AAD_AUTHENTICATED',
  AAD_LOGIN: 'AAD_LOGIN',
  AAD_LOGOUT: 'AAD_LOGOUT',
  AAD_SILENT_REFRESH: 'AAD_SILENT_REFRESH',
  AI_APPS_LOADED: 'AI_APPS_LOADED',
  LIST_AI_APPS: 'LIST_AI_APPS',
  LIST_AAD_SUBSCRIPTIONS: 'LIST_AAD_SUBSCRIPTIONS',
  SET_AAD_RESOURCE: 'SET_AAD_RESOURCE',
  SET_AAD_SUBSCRIPTION: 'SET_AAD_SUBSCRIPTION',
  AAD_SUBSCRIPTIONS_LOADED: 'AAD_SUBSCRIPTIONS_LOADED',
};